# Generated by Django 3.0.8 on 2020-08-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.CharField(choices=[('100', '100 (Philosophy)'), ('200', '200 (Religion)'), ('300', '300 (Social Science)'), ('400', '400 (Language)'), ('500', '500 (Pure Science)'), ('600', '600 (Applied Science)'), ('700', '700 (Art)'), ('800', '800 (Literature)'), ('900', '900 (History)')], max_length=4, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('subject_keyword', models.CharField(max_length=40, unique=True)),
                ('issued_date', models.DateField()),
                ('isbn', models.CharField(max_length=13)),
                ('isOnload', models.BooleanField()),
                ('reservation_number', models.IntegerField()),
            ],
        ),
    ]
