# Generated by Django 3.0.8 on 2020-08-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200803_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='class_number',
            field=models.CharField(choices=[('100 (Philosophy)', '100 (Philosophy)'), ('200 (Religion)', '200 (Religion)'), ('300 (Social Science)', '300 (Social Science)'), ('400 (Language)', '400 (Language)'), ('500 (Pure Science)', '500 (Pure Science)'), ('600 (Applied Science)', '600 (Applied Science)'), ('700 (Art)', '700 (Art)'), ('800 (Literature)', '800 (Literature)'), ('900 (History)', '900 (History)')], max_length=21, unique=True),
        ),
    ]
