# Generated by Django 3.0.8 on 2020-08-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200804_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='class_number',
            field=models.CharField(choices=[('100', '100 (Philosophy)'), ('200', '200 (Religion)'), ('300', '300 (Social Science)'), ('400', '400 (Language)'), ('500', '500 (Pure Science)'), ('600', '600 (Applied Science)'), ('700', '700 (Art)'), ('800', '800 (Literature)'), ('900', '900 (History)')], max_length=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject_keyword',
            field=models.CharField(max_length=40),
        ),
    ]
