# Generated by Django 3.0.8 on 2020-08-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200805_1006'),
        ('accounts', '0002_auto_20200803_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onloaded_books',
            field=models.ManyToManyField(blank=True, related_name='onloaded_books', to='books.Book'),
        ),
        migrations.AddField(
            model_name='user',
            name='reserved_books',
            field=models.ManyToManyField(blank=True, related_name='reserved_books', to='books.Book'),
        ),
    ]
