# Generated by Django 3.0.8 on 2020-08-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200805_1006'),
        ('accounts', '0003_auto_20200805_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onloading_books',
            field=models.ManyToManyField(blank=True, related_name='onloading_books', to='books.Book'),
        ),
    ]
