# Generated by Django 3.0.8 on 2020-08-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200805_1006'),
        ('accounts', '0004_user_onloading_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='onloading_books',
        ),
        migrations.AddField(
            model_name='user',
            name='loan_record',
            field=models.ManyToManyField(blank=True, related_name='loan_record', to='books.Book'),
        ),
    ]
